services:
  bwf-marker-extractor:
    build: .
    ports:
      - "3000:3000"
    # volumes:
      # Optional: Mount volumes for persistent storage (commented out to avoid permission issues)
      # - ./uploads:/usr/src/app/uploads
      # - ./outputs:/usr/src/app/outputs
      # Uncomment above if you want persistent storage, but ensure proper permissions
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_FILE_SIZE_MB=100
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - bwf-marker-extractor
  #   restart: unless-stopped